name: continuous_control
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.6
  - pytorch=1.6.0
  - cudatoolkit=10.1
  - torchvision=0.7.0
  - pip:
    - tensorflow==1.7.1
    - Pillow>=4.2.1
    - matplotlib
    - numpy>=1.11.0
    - jupyter
    - pytest>=3.2.2
    - docopt
    - pyyaml
    - protobuf==3.5.2
    - grpcio==1.11.0
    - pandas
    - scipy
    - ipykernel
    - unityagents
